version: "3"
services:
    db:
        image: postgres
        environment: 
            - "POSTGRES_USER=postgres"
            - "POSTGRES_PASSWORD=postgres"
            - "POSTGRES_DB=zelda_cookbook"
    zelda-cookbook-backend:
        build: ./zelda-cookbook-backend
        ports:
            - "81:3000"
    # front:
